import type { ClassifierShadowTrialFixture } from "./classifier-shadow-trial-fixture-types";
import {
  createClassifierShadowTrialFixture,
  type ClassifierShadowTrialFixtureDraft
} from "./classifier-shadow-trial-fixture-builders";

const gateFixtureDrafts: ClassifierShadowTrialFixtureDraft[] = [
  {
    id: "trial-openai-responses-sdk",
    sourceName: "OpenAI News",
    sourceTier: "auto-safe",
    title: "Responses SDK guide refresh",
    parsedSummary: "SDK guide refresh with migration steps and launch links.",
    tags: ["sdk", "release", "migration"],
    dedupeKey: "openai-responses-sdk-guide-refresh",
    expected: { targetSurface: "both", category: "sdk", adjudicatedConfidence: 0.9, rationale: "SDK launch belongs in both surfaces.", searchRequired: false },
    activePrediction: { targetSurface: "brief", category: "api", confidence: 0.84, latencyMs: 175 },
    candidatePrediction: { confidence: 0.92, latencyMs: 405 }
  },
  {
    id: "trial-openai-platform-rate-controls",
    sourceName: "OpenAI API Changelog",
    sourceTier: "auto-safe",
    title: "Platform rate control rollout",
    parsedSummary: "API platform control update with docs and operational impact.",
    tags: ["api", "release", "platform"],
    dedupeKey: "openai-platform-rate-control-rollout",
    expected: { targetSurface: "both", category: "api", adjudicatedConfidence: 0.89, rationale: "Operational API changes need brief and discover coverage.", searchRequired: false },
    activePrediction: { targetSurface: "brief", confidence: 0.86, latencyMs: 170 },
    candidatePrediction: { confidence: 0.91, latencyMs: 395 }
  },
  {
    id: "trial-anthropic-safety-note",
    sourceName: "Anthropic Research",
    sourceTier: "auto-safe",
    title: "Anthropic safety interpretation note",
    parsedSummary: "Research note with strong explanation value and weak outbound CTA.",
    tags: ["research", "safety"],
    dedupeKey: "anthropic-safety-interpretation-note",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.9, rationale: "Research memo fits the brief lane.", searchRequired: false },
    activePrediction: { confidence: 0.88, latencyMs: 150 },
    candidatePrediction: { confidence: 0.9, latencyMs: 350 }
  },
  {
    id: "trial-deepmind-eval-note",
    sourceName: "Google DeepMind",
    sourceTier: "auto-safe",
    title: "DeepMind evaluation note for agent teams",
    parsedSummary: "Official research explanation with low immediate CTA value.",
    tags: ["research", "evaluation"],
    dedupeKey: "deepmind-evaluation-note-agent-teams",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.88, rationale: "Best handled as a Korean brief explainer.", searchRequired: false },
    activePrediction: { confidence: 0.86, latencyMs: 155 },
    candidatePrediction: { confidence: 0.89, latencyMs: 355 }
  },
  {
    id: "trial-google-developers-gemini-api",
    sourceName: "Google Developers AI Blog",
    sourceTier: "auto-safe",
    title: "Gemini API rollout for developers",
    parsedSummary: "Developer API rollout with docs links and release framing.",
    tags: ["api", "release", "docs"],
    dedupeKey: "google-developers-gemini-api-rollout",
    expected: { targetSurface: "both", category: "api", adjudicatedConfidence: 0.88, rationale: "API launch should reach both explain and action surfaces.", searchRequired: false },
    activePrediction: { targetSurface: "brief", confidence: 0.85, latencyMs: 165 },
    candidatePrediction: { confidence: 0.9, latencyMs: 385 }
  },
  {
    id: "trial-huggingface-open-model-release",
    sourceName: "Hugging Face Blog",
    sourceTier: "auto-safe",
    title: "Open model release for workflow builders",
    parsedSummary: "Model and repo release with immediate visit and docs actions.",
    tags: ["open-source", "release", "repo"],
    dedupeKey: "huggingface-open-model-release",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.88, rationale: "Strong discover CTA item.", searchRequired: false },
    activePrediction: { confidence: 0.87, latencyMs: 145 },
    candidatePrediction: { confidence: 0.89, latencyMs: 305 }
  },
  {
    id: "trial-github-release-agent-router",
    sourceName: "GitHub Releases",
    sourceTier: "auto-safe",
    title: "Agent router release with install docs",
    parsedSummary: "Tracked repo release with clear GitHub and docs actions.",
    tags: ["open-source", "release", "repo"],
    dedupeKey: "github-release-agent-router-install-docs",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.89, rationale: "Release note belongs in discover.", searchRequired: false },
    activePrediction: { confidence: 0.88, latencyMs: 145 },
    candidatePrediction: { confidence: 0.9, latencyMs: 300 }
  },
  {
    id: "trial-github-release-design-plugin",
    sourceName: "GitHub Releases",
    sourceTier: "auto-safe",
    title: "Design plugin release with setup docs",
    parsedSummary: "Plugin release with immediate GitHub and documentation CTAs.",
    tags: ["open-source", "plugin", "release"],
    dedupeKey: "github-release-design-plugin-setup-docs",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.87, rationale: "Tool release is a clean discover item.", searchRequired: false },
    activePrediction: { confidence: 0.86, latencyMs: 148 },
    candidatePrediction: { confidence: 0.88, latencyMs: 302 }
  },
  {
    id: "trial-github-trending-browser-tool",
    sourceName: "GitHub Trending",
    sourceTier: "render-required",
    title: "Browser automation tool trends today",
    parsedSummary: "Trending repo with direct repo visit value and short summary need.",
    tags: ["open-source", "tool", "repo"],
    dedupeKey: "github-trending-browser-tool-today",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.86, rationale: "Trending repo should flow to radar.", searchRequired: false },
    activePrediction: { confidence: 0.85, latencyMs: 176 },
    candidatePrediction: { confidence: 0.87, latencyMs: 372 }
  },
  {
    id: "trial-github-trending-template-kit",
    sourceName: "GitHub Trending",
    sourceTier: "render-required",
    title: "Agent template kit spikes on GitHub Trending",
    parsedSummary: "Popular repo with GitHub CTA and low need for long-form briefing.",
    tags: ["open-source", "template", "repo"],
    dedupeKey: "github-trending-agent-template-kit",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.85, rationale: "Strong discover item for radar.", searchRequired: false },
    activePrediction: { confidence: 0.84, latencyMs: 178 },
    candidatePrediction: { confidence: 0.86, latencyMs: 375 }
  },
  {
    id: "trial-product-hunt-desktop-agent",
    sourceName: "Product Hunt AI",
    sourceTier: "render-required",
    title: "Desktop agent launch for personal workflows",
    parsedSummary: "Product page with launch CTA and site visit priority.",
    tags: ["website", "launch", "tool"],
    dedupeKey: "product-hunt-desktop-agent-launch",
    expected: { targetSurface: "discover", category: "website", adjudicatedConfidence: 0.86, rationale: "Launch page belongs in discover.", searchRequired: false },
    activePrediction: { category: "open_source", confidence: 0.82, latencyMs: 188, memoryFalsePositive: true },
    candidatePrediction: { confidence: 0.88, latencyMs: 405 }
  },
  {
    id: "trial-product-hunt-docs-workspace",
    sourceName: "Product Hunt AI",
    sourceTier: "render-required",
    title: "Docs workspace for agent teams launches",
    parsedSummary: "Website launch with site CTA and weak brief depth.",
    tags: ["website", "launch", "tool"],
    dedupeKey: "product-hunt-docs-workspace-launch",
    expected: { targetSurface: "discover", category: "website", adjudicatedConfidence: 0.85, rationale: "Direct-action website launch.", searchRequired: false },
    activePrediction: { category: "open_source", confidence: 0.81, latencyMs: 190, memoryFalsePositive: true },
    candidatePrediction: { confidence: 0.87, latencyMs: 408 }
  },
  {
    id: "trial-devpost-campus-hack",
    sourceName: "Devpost",
    sourceTier: "render-required",
    title: "Campus agent hack opens submissions",
    parsedSummary: "Competition page with apply CTA, deadline, and eligibility.",
    tags: ["contest", "apply", "event"],
    dedupeKey: "devpost-campus-agent-hack",
    expected: { targetSurface: "discover", category: "contest", adjudicatedConfidence: 0.85, rationale: "Competition page should use contest routing.", searchRequired: false },
    activePrediction: { category: "event", confidence: 0.83, latencyMs: 198, searchTriggered: true },
    candidatePrediction: { confidence: 0.86, latencyMs: 425 }
  },
  {
    id: "trial-kaggle-agent-competition",
    sourceName: "Kaggle Competitions",
    sourceTier: "render-required",
    title: "Agent competition opens on Kaggle",
    parsedSummary: "Competition page with apply CTA and leaderboard context.",
    tags: ["contest", "competition", "apply"],
    dedupeKey: "kaggle-agent-competition-open",
    expected: { targetSurface: "discover", category: "contest", adjudicatedConfidence: 0.86, rationale: "Discover contest item with apply CTA.", searchRequired: false },
    activePrediction: { category: "event", confidence: 0.82, latencyMs: 205, searchTriggered: true },
    candidatePrediction: { confidence: 0.87, latencyMs: 428 }
  },
  {
    id: "trial-ai-engineer-worlds-fair",
    sourceName: "AI Engineer World's Fair",
    sourceTier: "render-required",
    title: "World's Fair speaker lineup opens",
    parsedSummary: "Event page with site CTA and session overview value.",
    tags: ["event", "community", "conference"],
    dedupeKey: "ai-engineer-worlds-fair-speaker-lineup",
    expected: { targetSurface: "discover", category: "event", adjudicatedConfidence: 0.86, rationale: "Event registry item for discover.", searchRequired: false },
    activePrediction: { confidence: 0.86, latencyMs: 192 },
    candidatePrediction: { confidence: 0.87, latencyMs: 410 }
  },
  {
    id: "trial-mlh-hackathon-sprint",
    sourceName: "MLH",
    sourceTier: "render-required",
    title: "MLH spring sprint announcement",
    parsedSummary: "Hackathon announcement with deadline and apply CTA.",
    tags: ["event", "hackathon", "apply"],
    dedupeKey: "mlh-spring-sprint-announcement",
    expected: { targetSurface: "discover", category: "event", adjudicatedConfidence: 0.84, rationale: "Operationally handled as an event discover item.", searchRequired: false },
    activePrediction: { confidence: 0.84, latencyMs: 190 },
    candidatePrediction: { confidence: 0.85, latencyMs: 402 }
  },
  {
    id: "trial-openai-safety-rollout",
    sourceName: "OpenAI News",
    sourceTier: "auto-safe",
    title: "OpenAI safety rollout explainer",
    parsedSummary: "Policy and rollout explanation with limited outbound actions.",
    tags: ["research", "policy"],
    dedupeKey: "openai-safety-rollout-explainer",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.89, rationale: "Better as a brief explainer than radar item.", searchRequired: false },
    activePrediction: { confidence: 0.88, latencyMs: 152 },
    candidatePrediction: { confidence: 0.89, latencyMs: 345 }
  },
  {
    id: "trial-google-ai-benchmark-note",
    sourceName: "Google AI Blog",
    sourceTier: "auto-safe",
    title: "Google benchmark note for agent evaluation",
    parsedSummary: "Official blog post that mostly needs interpretation and context.",
    tags: ["research", "benchmark"],
    dedupeKey: "google-agent-evaluation-benchmark-note",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.88, rationale: "Research note fits brief surface.", searchRequired: false },
    activePrediction: { confidence: 0.86, latencyMs: 153 },
    candidatePrediction: { confidence: 0.88, latencyMs: 348 }
  },
  {
    id: "trial-huggingface-rag-tutorial",
    sourceName: "Hugging Face Blog",
    sourceTier: "auto-safe",
    title: "RAG tutorial note for builder teams",
    parsedSummary: "Tutorial-style post with explanation value higher than direct CTA value.",
    tags: ["research", "tutorial"],
    dedupeKey: "huggingface-rag-tutorial-builder-teams",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.86, rationale: "Best suited for brief interpretation.", searchRequired: false },
    activePrediction: { confidence: 0.85, latencyMs: 149 },
    candidatePrediction: { confidence: 0.87, latencyMs: 340 }
  },
  {
    id: "trial-transcript-manual-second",
    sourceName: "Transcript Mirror",
    sourceTier: "manual-review-required",
    title: "Transcript mirror on agent planning workflows",
    parsedSummary: "Long transcript with explanation value but provenance risk.",
    tags: ["analysis", "transcript"],
    dedupeKey: "transcript-mirror-agent-planning-workflows",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.8, rationale: "Brief candidate but manual review must stay on.", searchRequired: false },
    activePrediction: { confidence: 0.82, latencyMs: 162 },
    candidatePrediction: { confidence: 0.84, latencyMs: 388 }
  },
  {
    id: "trial-duplicate-release-second",
    sourceName: "GitHub Release Mirror",
    sourceTier: "auto-safe",
    title: "Second duplicate release mirror",
    parsedSummary: "Mirror of a repo release already tracked through the canonical source.",
    tags: ["duplicate", "repo", "release"],
    dedupeKey: "second-duplicate-release-mirror",
    expected: { targetSurface: "discard", category: "duplicate", adjudicatedConfidence: 0.92, rationale: "Duplicate should leave the pipeline immediately.", searchRequired: false },
    activePrediction: { targetSurface: "archive", category: "reference", confidence: 0.8, latencyMs: 172, memoryFalsePositive: true },
    candidatePrediction: { confidence: 0.9, latencyMs: 360 }
  },
  {
    id: "trial-archive-openai-note",
    sourceName: "OpenAI News",
    sourceTier: "auto-safe",
    title: "Archived rollout note",
    parsedSummary: "Internal reference note with memory value but no public promotion value.",
    tags: ["reference", "research"],
    dedupeKey: "archived-openai-rollout-note",
    expected: { targetSurface: "archive", category: "reference", adjudicatedConfidence: 0.9, rationale: "Archive-only reference item.", searchRequired: false },
    activePrediction: { confidence: 0.89, latencyMs: 148 },
    candidatePrediction: { targetSurface: "brief", category: "research", confidence: 0.84, latencyMs: 346 }
  },
  {
    id: "trial-openai-migration-guide",
    sourceName: "OpenAI API Changelog",
    sourceTier: "auto-safe",
    title: "Migration guide for platform teams",
    parsedSummary: "Migration guide with docs actions and explanation value.",
    tags: ["api", "migration", "docs"],
    dedupeKey: "openai-platform-migration-guide-teams",
    expected: { targetSurface: "both", category: "api", adjudicatedConfidence: 0.89, rationale: "Migration guides need both CTA and explain coverage.", searchRequired: false },
    activePrediction: { targetSurface: "brief", confidence: 0.86, latencyMs: 168 },
    candidatePrediction: { confidence: 0.9, latencyMs: 392 }
  },
  {
    id: "trial-anthropic-api-update",
    sourceName: "Anthropic Research",
    sourceTier: "auto-safe",
    title: "API-adjacent research update",
    parsedSummary: "Official update that blends research explanation with operational API relevance.",
    tags: ["api", "research", "release"],
    dedupeKey: "anthropic-api-adjacent-research-update",
    expected: { targetSurface: "both", category: "api", adjudicatedConfidence: 0.87, rationale: "Needs both brief and discover handling.", searchRequired: false },
    activePrediction: { targetSurface: "discover", category: "open_source", confidence: 0.82, latencyMs: 173 },
    candidatePrediction: { confidence: 0.89, latencyMs: 372 }
  },
  {
    id: "trial-github-release-benchmark-suite",
    sourceName: "GitHub Releases",
    sourceTier: "auto-safe",
    title: "Benchmark suite release with repo links",
    parsedSummary: "Tracked repo release with GitHub and docs CTAs.",
    tags: ["open-source", "release", "benchmark"],
    dedupeKey: "github-release-benchmark-suite-links",
    expected: { targetSurface: "discover", category: "open_source", adjudicatedConfidence: 0.88, rationale: "Release-oriented discover item.", searchRequired: false },
    activePrediction: { confidence: 0.87, latencyMs: 147 },
    candidatePrediction: { confidence: 0.89, latencyMs: 304 }
  },
  {
    id: "trial-product-hunt-agent-dashboard",
    sourceName: "Product Hunt AI",
    sourceTier: "render-required",
    title: "Agent dashboard launch hits Product Hunt",
    parsedSummary: "Website launch with site CTA and low brief value.",
    tags: ["website", "launch", "tool"],
    dedupeKey: "product-hunt-agent-dashboard-launch",
    expected: { targetSurface: "discover", category: "website", adjudicatedConfidence: 0.86, rationale: "Direct discover launch item.", searchRequired: false },
    activePrediction: { category: "open_source", confidence: 0.82, latencyMs: 191, memoryFalsePositive: true },
    candidatePrediction: { confidence: 0.88, latencyMs: 412 }
  },
  {
    id: "trial-devpost-student-challenge",
    sourceName: "Devpost",
    sourceTier: "render-required",
    title: "Student agent challenge opens",
    parsedSummary: "Contest page with apply CTA and schedule metadata.",
    tags: ["contest", "apply", "students"],
    dedupeKey: "devpost-student-agent-challenge-opens",
    expected: { targetSurface: "discover", category: "contest", adjudicatedConfidence: 0.85, rationale: "Contest lane with clear CTA.", searchRequired: false },
    activePrediction: { confidence: 0.85, latencyMs: 198 },
    candidatePrediction: { confidence: 0.86, latencyMs: 420 }
  },
  {
    id: "trial-kaggle-dataset-sprint",
    sourceName: "Kaggle Competitions",
    sourceTier: "render-required",
    title: "Dataset sprint competition opens",
    parsedSummary: "Competition page with deadline, leaderboard, and apply action.",
    tags: ["contest", "competition", "dataset"],
    dedupeKey: "kaggle-dataset-sprint-opens",
    expected: { targetSurface: "discover", category: "contest", adjudicatedConfidence: 0.86, rationale: "Competition should stay in discover/contest.", searchRequired: false },
    activePrediction: { category: "event", confidence: 0.83, latencyMs: 204, searchTriggered: true },
    candidatePrediction: { confidence: 0.87, latencyMs: 426 }
  },
  {
    id: "trial-google-deepmind-lab-note",
    sourceName: "Google DeepMind",
    sourceTier: "auto-safe",
    title: "DeepMind lab note on agent memory",
    parsedSummary: "Research-heavy post with explanation value and limited outbound CTA value.",
    tags: ["research", "memory"],
    dedupeKey: "deepmind-lab-note-agent-memory",
    expected: { targetSurface: "brief", category: "research", adjudicatedConfidence: 0.89, rationale: "Research note best handled as a brief.", searchRequired: false },
    activePrediction: { confidence: 0.88, latencyMs: 154 },
    candidatePrediction: { confidence: 0.9, latencyMs: 352 }
  }
];

export const classifierShadowTrialGateFixtures: ClassifierShadowTrialFixture[] = gateFixtureDrafts.map(
  createClassifierShadowTrialFixture
);
