insert into public.sources (
  name,
  kind,
  base_url,
  source_tier,
  enabled,
  failure_reason,
  feed_url,
  content_type,
  default_tags,
  max_items,
  fetch_kind,
  pipeline_lane
)
values
  (
    'Landing Love',
    'rss',
    'https://www.landing.love/',
    'auto-safe',
    true,
    null,
    'https://www.landing.love/index.xml',
    'article',
    array['design', 'landing-page', 'inspiration'],
    3,
    'rss',
    'editorial'
  ),
  (
    'Codrops',
    'rss',
    'https://tympanus.net/codrops/',
    'auto-safe',
    true,
    null,
    'https://tympanus.net/codrops/feed/',
    'article',
    array['design', 'css', 'animation', 'interaction'],
    3,
    'rss',
    'editorial'
  ),
  (
    'Awwwards Blog',
    'rss',
    'https://www.awwwards.com/blog/',
    'auto-safe',
    true,
    null,
    'https://www.awwwards.com/blog/feed/',
    'article',
    array['design', 'award', 'inspiration'],
    3,
    'rss',
    'editorial'
  ),
  (
    'CSS-Tricks',
    'rss',
    'https://css-tricks.com/',
    'auto-safe',
    true,
    null,
    'https://css-tricks.com/feed/',
    'article',
    array['design', 'css', 'frontend'],
    3,
    'rss',
    'editorial'
  ),
  (
    'Smashing Magazine',
    'rss',
    'https://www.smashingmagazine.com/',
    'auto-safe',
    true,
    null,
    'https://www.smashingmagazine.com/feed/',
    'article',
    array['design', 'ux', 'frontend'],
    3,
    'rss',
    'editorial'
  ),
  (
    'Nielsen Norman Group',
    'rss',
    'https://www.nngroup.com/',
    'auto-safe',
    true,
    null,
    'https://www.nngroup.com/feed/rss/',
    'article',
    array['ux', 'research', 'pattern'],
    3,
    'rss',
    'editorial'
  ),
  (
    'A List Apart',
    'rss',
    'https://alistapart.com/',
    'auto-safe',
    true,
    null,
    'https://alistapart.com/main/feed/',
    'article',
    array['design', 'web', 'editorial'],
    3,
    'rss',
    'editorial'
  ),
  (
    'Logo Design Love',
    'rss',
    'https://www.logodesignlove.com/',
    'auto-safe',
    true,
    null,
    'https://www.logodesignlove.com/feed',
    'article',
    array['design', 'logo', 'brand'],
    3,
    'rss',
    'editorial'
  )
on conflict (pipeline_lane, name) do update set
  kind = excluded.kind,
  base_url = excluded.base_url,
  source_tier = excluded.source_tier,
  feed_url = excluded.feed_url,
  content_type = excluded.content_type,
  default_tags = excluded.default_tags,
  max_items = excluded.max_items,
  fetch_kind = excluded.fetch_kind,
  enabled = public.sources.enabled,
  failure_reason = coalesce(public.sources.failure_reason, excluded.failure_reason);
